---
roles_path: ./roles
driver:
  customize:
    memory: 2048

driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: ndenv
    run_list:
      - role[nodejs]
  - name: phpenv
    run_list:
      - role[php]
  - name: pyenv
    run_list:
      - role[python]
  - name: rbenv
    run_list:
      - role[ruby]
  - name: jenv
    run_list:
      - role[java]
