---
driver_plugin: openstack
driver_config:
  name: openstack
  openstack_username: "<%= ENV['KITCHEN_OS_USERNAME'] %>"
  openstack_api_key: "<%= ENV['KITCHEN_OS_PASSWORD'] %>"
  openstack_auth_url: "<%= ENV['KITCHEN_OS_AUTH_URL'] %>"
  openstack_identity_endpoint: "<%= ENV['KITCHEN_OS_AUTH_URL'] %>"
  openstack_tenant: "<%= ENV['KITCHEN_OS_TENANT_NAME'] %>"
  key_name: "<%= ENV['KITCHEN_OS_KEY_NAME'] %>"
  private_key_path: "<%= ENV['PWD'] %>/.kitchen.key"
  floating_ip_pool: "<%= ENV['KITCHEN_OS_FLOATING_IP_POOL'] %>"
  flavor_ref: "<%= ENV['KITCHEN_OS_FLV_1_vCPU_RAM_1G'] %>"
  username: stack

platforms:
  - name: ubuntu-12.04
    driver_config:
      image_ref: <%= ENV['KITCHEN_OS_IMG_UBUNTU1204'] %>
  - name: ubuntu-14.04
    driver_config:
      image_ref: <%= ENV['KITCHEN_OS_IMG_UBUNTU1404'] %>

suites:
  - name: ndenv
    run_list:
      - recipe[container::ndenv]
  - name: phpenv
    run_list:
      - recipe[container::phpenv]
  - name: pyenv
    run_list:
      - recipe[container::pyenv]
  - name: rbenv
    run_list:
      - recipe[container::rbenv]
    excludes:
      - ubuntu-14.04
  - name: jenv
    run_list:
      - recipe[container::jenv]
